### ISSUE TITLE
map updates from mireo

### ISSUE THREAD

**Issue by tido-** [mireo/map-report#1]
Dear Sir or Madam,

The version number looks a bit weird and since the last update (2020) some time has passed. Will you update these map files again? 
I got the maps from http://partners.mireo.hr/crm

Thank you for your information - I soon go on a travel and so I looked for the latest version.  

--- 
![grafik](https://user-images.githubusercontent.com/10658438/224490151-7ca87436-ae78-425d-a762-ef1d028c574f.png)

**Comment by sskarabej** [comment]
The reported issue is not related to this project.
